### ISSUE TITLE
SpinJSSpinner is not a function

### ISSUE THREAD

**Issue by jongunterfv** [rpocklin/angular-ui-view-spinner#4]
Tried to install it, but no spinner appeared. Got:

```
TypeError: SpinJSSpinner is not a function
    at Object.<anonymous> (http://localhost:54317/node_modules/angular-spinner/angular-spinner.js:90:24)
    at Object.arguments.(anonymous function) [as fn] (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1953:36)
    at Scope.$digest (http://localhost:54317/Scripts/angular.js:15826:29)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1972:23)
    at Scope.$apply (http://localhost:54317/Scripts/angular.js:16097:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2035:22)
    at bootstrapApply (http://localhost:54317/Scripts/angular.js:1660:15)
    at Object.invoke (http://localhost:54317/Scripts/angular.js:4478:17)
    at doBootstrap (http://localhost:54317/Scripts/angular.js:1658:14)
    at Object.angular.resumeBootstrap (http://localhost:54317/Scripts/angular.js:1686:12)
```

**Comment by rpocklin** [comment]
There's stuff in your stacktrace around chrome extensions, can I suggest you try an incognito window?
Can you get the example working?  You may need to share some more code to give me a clue.

This library is dependent on spin.js, check that that's been included in your `index.html` along with this library.
